# Generated by Django 4.0.4 on 2022-05-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de usuario')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre usuario')),
                ('correo', models.CharField(max_length=20, verbose_name='Correo usuario')),
                ('telefono', models.IntegerField(verbose_name='Numero telefono')),
                ('password', models.CharField(max_length=12, verbose_name='Password usuario')),
            ],
        ),
    ]
