# Generated by Django 4.0.4 on 2022-06-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuario_idusuario_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Correo usuario'),
        ),
    ]
